---
 - name: installation apache
   apt:
     name: apache2
     update_cache: yes
     state: latest

 - name: Start
   service:
     name: apache2
     state: started
     enabled: True

 - name: Configuratoin site 1
   include:  site.yml
... 
